# Configuración de la base de datos Azure SQL
spring.datasource.url=jdbc:sqlserver://sql-exoal-prototipo.database.windows.net:1433;database=db-exoal-prototipo;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.username=admin_exoal
spring.datasource.password=P@ssw0rd123!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Configuración JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Puerto del servidor
server.port=8080